export type ChartType = 'line' | 'bar' | 'sparkline' | 'text'

export type EntranceStyle = 'fly-in' | 'dissolve' | 'sparkle' | 'typewriter'

export interface DataPoint {
  label: string
  value: number
}

// ---------------------------------------------------------------------------
// Dot color descriptors
// ---------------------------------------------------------------------------

/** Solid fill — every dot in the segment is the same color. */
export interface DotColorSolid {
  type: 'solid'
  /** CSS hex string, e.g. "#ff6600". Named colors are resolved in parse-viz. */
  hex: string
}

/**
 * Rainbow — hue cycles continuously across the horizontal dot position
 * of the entire rendered display, so the rainbow spans the full width
 * regardless of word boundaries.
 */
export interface DotColorRainbow {
  type: 'rainbow'
}

/**
 * Linear gradient — color interpolates from `from` to `to` across the
 * leftmost to rightmost rendered dot column of this segment.
 */
export interface DotColorGradient {
  type: 'gradient'
  from: string  // CSS hex
  to: string    // CSS hex
}

export type DotColor = DotColorSolid | DotColorRainbow | DotColorGradient

// ---------------------------------------------------------------------------
// Sprite map
// ---------------------------------------------------------------------------

/**
 * A sparse dot-color map produced by the image-to-sprite converter.
 * key = "row,col", value = CSS hex color (e.g. "#ff6600").
 * Only lit dots are present; absent keys are treated as unlit.
 */
export type SpriteMap = Map<string, string>

/**
 * JSON-serialisable form of SpriteMap for SQLite storage and wire transfer.
 * Converted to/from Map at the DB/API boundary.
 */
export type SpriteData = Record<string, string>

// ---------------------------------------------------------------------------
// Billboard segments
// ---------------------------------------------------------------------------

/**
 * Text segment — a block of billboard copy with its own dot color.
 * The `type` field is optional for backward compatibility with existing
 * `{ text, color }` objects; absent type is treated as 'text'.
 */
export interface BillboardSegmentText {
  type?: 'text'
  text: string
  color: DotColor
}

/**
 * Sprite segment — a raster image converted to a per-dot color map.
 * Placed by the whitespace-detection pass in DotMatrixDisplay.
 */
export interface BillboardSegmentSprite {
  type: 'sprite'
  spriteMap: SpriteMap
}

/**
 * Portrait segment — a color-banded approximation generated from palette
 * colors returned by the LLM for character-sheet queries.
 */
export interface BillboardSegmentPortrait {
  type: 'portrait'
  /** 1–4 palette colors, rendered as equal-height horizontal bands top-to-bottom. */
  colors: string[]
}

export type BillboardSegment =
  | BillboardSegmentText
  | BillboardSegmentSprite
  | BillboardSegmentPortrait

// ---------------------------------------------------------------------------
// Visualization data
// ---------------------------------------------------------------------------

export interface VisualizationData {
  chartType: ChartType
  title: string
  /** One-line plain-text summary shown in the footer */
  summary: string
  /** Present for chart types (line/bar/sparkline) */
  dataPoints: DataPoint[]
  /**
   * Billboard copy split into 1–3 display segments.
   * Each segment starts on its own row group and is drawn with its dot color.
   * Always populated for chartType "text".
   */
  segments?: BillboardSegmentText[]
  /** Legacy flat copy — kept for backward compat; prefer segments */
  words?: string
  /** Optional unit string, e.g. "$", "%", "ms" */
  unit?: string
  /** Entrance animation style chosen by the LLM. */
  entranceStyle?: EntranceStyle
  /**
   * LLM-generated visual description of the subject, written for an
   * image-generation model. Absent for abstract/data queries.
   */
  visualDescription?: string
  /**
   * Sprite generated by EverArt for this billboard.
   * Stored as a SpriteData (plain object) for SQLite and wire transfer.
   */
  generatedSpriteData?: SpriteData
}

/**
 * A single item in the user's billboard playlist.
 * Created when a query completes; chatId enables deletion of the OpenRAG conversation.
 */
export interface BillboardItem {
  id: string
  query: string
  /** chatId returned by OpenRAG — null if the stream didn't return one */
  chatId: string | null
  data: VisualizationData
  /** Base64-encoded mp3 generated at query time — null if unavailable */
  audioB64: string | null
  /**
   * Serialised SpriteMap for a user-uploaded logo image.
   * null when no logo has been uploaded for this item.
   */
  spriteData: SpriteData | null
}

export type BillboardPhase =
  | { phase: 'setup' }
  | { phase: 'idle' }
  | { phase: 'loading'; query: string; tokenCount: number; streamText: string }
  | { phase: 'transitioning'; next: VisualizationData; audioB64: string | null }
  | { phase: 'displaying'; data: VisualizationData; dwellRemaining: number }
  | { phase: 'error'; message: string; query: string }
  | { phase: 'manual'; query: string; tokenCount: number; streamText: string }
